language: python
branches:
  only:
  - master
install:
- pip install pelican ghp-import pelican-gist markdown
script:
- make publish github

env:
    global:
        secure: "ZyZiCTMqk4Zv56V8wJ2N3CD/+gj3YOTdBs20JRJi387Z3c6llSkVDv/sV8gjJjcMZ7GUt+9Fa2NFkik4ICYzNrrsB6f2ZH7tZmdcwErd3VZZ4mbtAC3BzbTlpmVxbaGxVJoALBvrLJU5HXBhc/RH8sZ5pF0RDAok2FmBAbm/6G+4FvmbBzgM1GFBydZHx4SFfgM1Jf/FB4W/hRYjUJQlipKhnsq0UQNgo6ga3kPTm94LriC5zgAj0bOXOQTuryuy2BCvHn5i6eZONirxcI+UYtGlYVg3aezqqbf9Q0apGmBbY7TWSq9K6Q9ftk7YJ97wYB5+JdnGzuAeuF95tVRm7giCBNaYJ0/p1gp6Ygp3yMcFqvaricHCs9o9fdVB1EOgZ3343325kcVf5/qQZTxs5jkhXk26SKxJ3DWudSsxqq/Y0L/uWKUmDAJCkgYeSzkAuGBZY8rrcR6aAOXaB55vCtUmy+1+AKU4wreF8o/A3XunvvjvKea8psrCvL4txK4P629/odDwyPBglbBqKJmzLDCJkz0Up4NOBauMOqubmkqj8RqStiYOv9V5srUCF6mXmceaDXIDayH96k8eqAYs9wK2g3kt0TtpywKR7gI/bL4QN6tWoH4l4uP9/khS6ce7ph3DOKDaU4z590LPSs5pWX9VJWUsg42kmAipz+L7rWg="
